name = "worker"
type = "javascript"
zone_id = ""
account_id = "ef534bb0b9d4d86b7ffd980dd56f5761"
route = ""
workers_dev = true

[vars]
NOTION_TOKEN="secret_QZ7qH2fIHN7bNx2eq2CedqeKnizg9jrx60tPNoL5QCd"
NOTION_DATABASE_ID="9bdf0d9244db40ceafc1aefc8886f35e"
DATABASE_TITLE_PROPERTY_NAME="name"
DATABASE_JUSTWATCH_PROPERTY_NAME="Where to watch"
JUSTWATCH_PROVIDERS="2,8,9,337"

[build]
command = "npm install && npm run worker-build"
[build.upload]
format = "service-worker"
